[build]
  publish = "."

[[redirects]]
  from = "http://www.passfasteruk.co.uk/*"
  to = "https://passfasteruk.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.passfasteruk.co.uk/*"
  to = "https://passfasteruk.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/:slug.html"
  to = "/:slug"
  status = 301

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/:slug"
  to = "/:slug.html"
  status = 200
